name: First CIC
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install express
        run: npm install express

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

      - name: Run build
        run: npm run build --if-present

      - name: Run test
        run: npm test

      # - name: Run the app
      #   run: node app.js
