name: First CICD
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
    GITHUB_RUN_ID: ${{github.run_id}}
    GITHUB_RUN_NUMBER: ${{github.run_number}}
    GITHUB_ACTOR: ${{github.actor}}
    GITHUB_WORKFLOW: ${{github.workflow}}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:         
      pull-requests: write
      contents: write

    outputs:
      output_test: ${{ steps.test.outcome }}
      output_lint: ${{ steps.linter.outcome }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install dependencies
        run: |
            npm install -g express-generator
            npm install express 
            npm install
            npm install --save-dev jest supertest

      - name: Run linter
        id: linter
        uses: super-linter/super-linter@v6.6.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true

      - name: Run build
        id: build
        continue-on-error: true
        run: npm run build --if-present
        
      - name: Run test
        id: test
        continue-on-error: true
        run: npm run test

      - name: Archive Artifact
        id: archive_artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: hello-artifact
          path: | 
            *
            !.**
            !node_modules
          retention-days: 1    

      - name: update Comments
        run: |
          printf "linter output: ${{toJson(steps.linter)}}\n
          test output: ${{toJson(steps.test)}}\n
          build output: ${{toJson(steps.build)}}\n
          artifact output: ${{toJson(steps.archive_artifact)}}\n
          Run ID: $GITHUB_RUN_ID\n
          Run NUmber: $GITHUB_RUN_NUMBER\n
          Actor: $GITHUB_ACTOR\n
          Workflow: $GITHUB_WORKFLOW"   

  # Deploy job
  deploy:
    needs: build

    concurrency:
      group: "pages"
      cancel-in-progress: false

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:         
      pull-requests: write
      contents: write
      pages: write 
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: UPDATE README
        id: readme
        continue-on-error: true
        run: |
          printf "![Test](https://img.shields.io/badge/Test-${{needs.build.outputs.output_test}}-93b023?&style=for-the-badge) | 
                ![Lint](https://img.shields.io/badge/Lint-${{needs.build.outputs.output_lint}}-blue?&style=for-the-badge)\n\n
                ![pages published here] (${{steps.deployment.outputs.page_url}})" > README.md

      - name: pull-request
        uses: repo-sync/pull-request@v2
        id: pull_request
        continue-on-error: true
        with:
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: commit
        id: commit_change
        continue-on-error: true
        run: |
          git config --global user.email ${{secrets.email}}
          git config --global user.name ${{secrets.username}}
          git add .
          git commit -m "new commit from ${{github.event.pusher.name}}, commit no: $GITHUB_RUN_NUMBER"
          
      - name: Push changes
        if: ${{needs.build.outputs.output_test == 'success'}}
        continue-on-error: true
        uses: ad-m/github-push-action@master
        id: push_changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
      - name: update Comment on Deployment
        run: |
          printf "deployment output: ${{toJson(steps.deployment)}}\n
          readme output: ${{toJson(steps.readme)}}\n
          pullRequest output: ${{toJson(steps.pull_request)}}\n
          commit output: ${{toJson(steps.commit_change)}}\n
          push output: ${{toJson(steps.push_changes)}}\n
          pages published at: ${{ steps.deployment.outputs.page_url }}"