name: First CICD
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install express
        run: npm install express

      - name: Run linters
        id: linter
        uses: wearerequired/lint-action@v2
        continue-on-error: true
        with:
          eslint: true

      - name: Run build
        id: build
        continue-on-error: true
        run: npm run build --if-present
        

      - name: Run test
        id: test
        continue-on-error: true
        run: npm test

      - name: Archive Artifact
        id: archive-artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: hello-artifact
          path: archive_folder

      - name: Create an issue
        # if: github.actions.checkout.pull_request && failure()
        if: failure()
        steps:
         - name: Check if issue already exists
           uses: actions/find-issues@v2
           id: find-issues
           with:
              query: |
                label:"error"
                state:open
                issue_number: ${{ github.issue.number }}
          
         - name: Create issue from PR
           if: steps.find-issues.outputs.issues == '[]'      
           uses: actions/create-issue@v2
           with:
              title: 'Error in workflow: ${{ github.workflow }}'
              assignee: ${{ payload.sender.login }},
              body: |
                Error message: ${{ github.actions.error.message }}
                PR: ${{ github.pull_request.html_url }}
                Workflow: ${{ github.workflow.html_url }}
                labels: 'error, workflow'
                issue_number: ${{ github.issue.number }}

      - name: Delete an issue
        # if: github.actions.checkout.pull_request && failure()
        if: github.issue.state == 'closed'
        steps:
          - uses: actions/delete-issue@v2
            with:
              issue_number: ${{ github.issue.number }}


      # - name: Run the app
      #   run: node app.js
